package com.example.clouddisk.util;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;
import org.springframework.web.multipart.MultipartFile;

import java.io.*;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;

/**
 *  * HDFS 操作工具类
 *   * 封装：初始化配置、文件上传、下载、删除、列表查询
 *    */
@Component // 交给 Spring 容器管理，方便后续注入使用
public class HdfsUtil {

    // 从 application.yml 读取 Hadoop 配置路径
    //     @Value("${hadoop.config-path}")
    //         private String hadoopConfigPath;
    //
    //             // 从 application.yml 读取 HDFS 云盘根路径
    //                 @Value("${hadoop.hdfs-path}")
    //                     private String hdfsRootPath;
    //
    //                         // HDFS 文件系统客户端（单例）
    //                             private FileSystem fileSystem;
    //
    //                                 /**
    //                                      * 初始化 HDFS 配置及客户端（懒加载，首次使用时初始化）
    //                                           * @throws Exception 初始化异常
    //                                                */
    //                                                    private void initHdfs() throws Exception {
    //                                                            if (fileSystem == null) {
    //                                                                        // 1. 创建 Hadoop 配置对象
    //                                                                                    Configuration conf = new Configuration();
    //                                                                                                // 2. 加载 Hadoop 核心配置文件（core-site.xml、hdfs-site.xml）
    //                                                                                                            conf.addResource(new Path(hadoopConfigPath + "/core-site.xml"));
    //                                                                                                                        conf.addResource(new Path(hadoopConfigPath + "/hdfs-site.xml"));
    //                                                                                                                                    // 3. 获取 HDFS 文件系统客户端
    //                                                                                                                                                URI hdfsUri = new URI(hdfsRootPath);
    //                                                                                                                                                            fileSystem = FileSystem.get(hdfsUri, conf, "root"); // root 为服务器用户名
    //                                                                                                                                                                    }
    //                                                                                                                                                                        }
    //
    //                                                                                                                                                                            /**
    //                                                                                                                                                                                 * 文件上传：上传 MultipartFile 到 HDFS 的 /cloud-disk/用户ID/ 目录
    //                                                                                                                                                                                      * @param file 前端上传的文件
    //                                                                                                                                                                                           * @param userId 用户ID（文件归属用户）
    //                                                                                                                                                                                                * @return HDFS 中的文件完整路径（如：hdfs://hadoop1:9000/cloud-disk/1/test.txt）
    //                                                                                                                                                                                                     * @throws Exception 上传异常
    //                                                                                                                                                                                                          */
    //                                                                                                                                                                                                              public String uploadFile(MultipartFile file, Long userId) throws Exception {
    //                                                                                                                                                                                                                      // 1. 初始化 HDFS 客户端
    //                                                                                                                                                                                                                              initHdfs();
    //
    //                                                                                                                                                                                                                                      // 2. 构建用户专属目录（/cloud-disk/用户ID/）
    //                                                                                                                                                                                                                                              String userDir = hdfsRootPath + "/" + userId;
    //                                                                                                                                                                                                                                                      Path userDirPath = new Path(userDir);
    //
    //                                                                                                                                                                                                                                                              // 3. 若用户目录不存在，创建目录
    //                                                                                                                                                                                                                                                                      if (!fileSystem.exists(userDirPath)) {
    //                                                                                                                                                                                                                                                                                  fileSystem.mkdirs(userDirPath);
    //                                                                                                                                                                                                                                                                                              // 设置目录权限 777（可选，避免权限问题）
    //                                                                                                                                                                                                                                                                                                          fileSystem.setPermission(userDirPath, new FsPermission((short) 0777));
    //                                                                                                                                                                                                                                                                                                                  }
    //
    //                                                                                                                                                                                                                                                                                                                          // 4. 构建文件完整路径（用户目录 + 原文件名）
    //                                                                                                                                                                                                                                                                                                                                  String fileName = file.getOriginalFilename();
    //                                                                                                                                                                                                                                                                                                                                          String hdfsFilePath = userDir + "/" + fileName;
    //                                                                                                                                                                                                                                                                                                                                                  Path hdfsFileFullPath = new Path(hdfsFilePath);
    //
    //                                                                                                                                                                                                                                                                                                                                                          // 5. 上传文件（将 MultipartFile 转换为输入流，写入 HDFS）
    //                                                                                                                                                                                                                                                                                                                                                                  try (InputStream inputStream = file.getInputStream();
    //                                                                                                                                                                                                                                                                                                                                                                               FSDataOutputStream outputStream = fileSystem.create(hdfsFileFullPath, true)) {
    //
    //                                                                                                                                                                                                                                                                                                                                                                                           byte[] buffer = new byte[1024 * 1024]; // 1MB 缓冲区
    //                                                                                                                                                                                                                                                                                                                                                                                                       int len;
    //                                                                                                                                                                                                                                                                                                                                                                                                                   while ((len = inputStream.read(buffer)) != -1) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                   outputStream.write(buffer, 0, len);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                               }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                           outputStream.flush();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // 6. 返回 HDFS 文件完整路径
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return hdfsFilePath;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 文件下载：从 HDFS 下载文件到本地输入流（供前端下载）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * @param hdfsFilePath HDFS 文件完整路径
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @return 本地输入流（前端可通过该流下载文件）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * @throws Exception 下载异常
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public InputStream downloadFile(String hdfsFilePath) throws Exception {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 1. 初始化 HDFS 客户端
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        initHdfs();
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 2. 构建 HDFS 文件路径
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Path hdfsFileFullPath = new Path(hdfsFilePath);
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 3. 校验文件是否存在
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (!fileSystem.exists(hdfsFileFullPath)) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    throw new FileNotFoundException("HDFS 文件不存在：" + hdfsFilePath);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 4. 打开文件输入流
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            FSDataInputStream inputStream = fileSystem.open(hdfsFileFullPath);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return inputStream;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 文件删除：删除 HDFS 中的指定文件
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      * @param hdfsFilePath HDFS 文件完整路径
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * @return true：删除成功；false：删除失败
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * @throws Exception 删除异常
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         public boolean deleteFile(String hdfsFilePath) throws Exception {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 1. 初始化 HDFS 客户端
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         initHdfs();
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 2. 构建 HDFS 文件路径
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Path hdfsFileFullPath = new Path(hdfsFilePath);
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // 3. 校验文件是否存在
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (!fileSystem.exists(hdfsFileFullPath)) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     throw new FileNotFoundException("HDFS 文件不存在：" + hdfsFilePath);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // 4. 删除文件（true：递归删除，支持删除目录；此处仅删除文件，效果一致）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             boolean isDeleted = fileSystem.delete(hdfsFileFullPath, true);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return isDeleted;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  * 列表查询：查询指定用户在 HDFS 中的所有文件信息（文件名、大小、路径）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       * @param userId 用户ID
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            * @return 文件信息列表（每个元素为文件名:文件大小:文件路径）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @throws Exception 查询异常
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          public List<String> listUserFiles(Long userId) throws Exception {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 1. 初始化 HDFS 客户端
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          initHdfs();
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // 2. 构建用户专属目录
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          String userDir = hdfsRootPath + "/" + userId;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Path userDirPath = new Path(userDir);
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 3. 校验用户目录是否存在
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (!fileSystem.exists(userDirPath)) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return new ArrayList<>(); // 目录不存在，返回空列表
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // 4. 列出目录下所有文件（不递归查询子目录）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      RemoteIterator<LocatedFileStatus> fileIterator = fileSystem.listFiles(userDirPath, false);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              List<String> fileList = new ArrayList<>();
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // 5. 遍历文件，封装文件信息
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while (fileIterator.hasNext()) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          LocatedFileStatus fileStatus = fileIterator.next();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      String fileName = fileStatus.getPath().getName(); // 文件名
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  long fileSize = fileStatus.getLen(); // 文件大小（字节）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              String fileFullPath = fileStatus.getPath().toString(); // 文件完整路径
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // 封装信息（格式：文件名:文件大小:文件路径），后续可替换为实体类
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      String fileInfo = fileName + ":" + fileSize + ":" + fileFullPath;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fileList.add(fileInfo);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return fileList;
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               * 关闭 HDFS 客户端（Spring 容器销毁时自动调用）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * @throws Exception 关闭异常
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             @Override
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 protected void finalize() throws Exception {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (fileSystem != null) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     fileSystem.close();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
