package com.example.clouddisk.controller;

import com.example.clouddisk.entity.FileMetadata;
import com.example.clouddisk.mapper.FileMetadataMapper;
import com.example.clouddisk.util.HdfsUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.io.InputStream;
import java.util.Date;
import java.util.List;

/**
 *  * 文件操作核心接口
 *   * 包含：上传、列表、下载、删除
 *    */
@RestController
@RequestMapping("/api/file") // 接口统一前缀
public class FileController {

    // 注入 HDFS 工具类
    //     @Autowired
    //         private HdfsUtil hdfsUtil;
    //
    //             // 注入 FileMetadata Mapper（数据库操作）
    //                 @Autowired
    //                     private FileMetadataMapper fileMetadataMapper;
    //
    //                         /**
    //                              * 接口1：文件上传
    //                                   * @param file 前端上传的文件
    //                                        * @param userId 用户ID
    //                                             * @return 上传结果
    //                                                  */
    //                                                      @PostMapping("/upload")
    //                                                          public ResponseEntity<String> uploadFile(@RequestParam("file") MultipartFile file,
    //                                                                                                       @RequestParam("userId") Long userId) {
    //                                                                                                               try {
    //                                                                                                                           // 1. 校验文件是否为空
    //                                                                                                                                       if (file.isEmpty()) {
    //                                                                                                                                                       return new ResponseEntity<>("上传失败：文件为空", HttpStatus.BAD_REQUEST);
    //                                                                                                                                                                   }
    //
    //                                                                                                                                                                               // 2. 调用 HDFS 工具类上传文件，获取 HDFS 文件路径
    //                                                                                                                                                                                           String hdfsFilePath = hdfsUtil.uploadFile(file, userId);
    //
    //                                                                                                                                                                                                       // 3. 封装文件元数据
    //                                                                                                                                                                                                                   FileMetadata fileMetadata = new FileMetadata();
    //                                                                                                                                                                                                                               fileMetadata.setFileName(file.getOriginalFilename());
    //                                                                                                                                                                                                                                           fileMetadata.setFilePath(hdfsFilePath);
    //                                                                                                                                                                                                                                                       fileMetadata.setFileSize(file.getSize());
    //                                                                                                                                                                                                                                                                   fileMetadata.setUserId(userId);
    //                                                                                                                                                                                                                                                                               fileMetadata.setUploadTime(new Date());
    //
    //                                                                                                                                                                                                                                                                                           // 4. 插入元数据到 MySQL 数据库
    //                                                                                                                                                                                                                                                                                                       fileMetadataMapper.insert(fileMetadata);
    //
    //                                                                                                                                                                                                                                                                                                                   return new ResponseEntity<>("上传成功：" + hdfsFilePath, HttpStatus.OK);
    //                                                                                                                                                                                                                                                                                                                           } catch (Exception e) {
    //                                                                                                                                                                                                                                                                                                                                       e.printStackTrace();
    //                                                                                                                                                                                                                                                                                                                                                   return new ResponseEntity<>("上传失败：" + e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
    //                                                                                                                                                                                                                                                                                                                                                           }
    //                                                                                                                                                                                                                                                                                                                                                               }
    //
    //                                                                                                                                                                                                                                                                                                                                                                   /**
    //                                                                                                                                                                                                                                                                                                                                                                        * 接口2：文件列表查询（根据用户ID）
    //                                                                                                                                                                                                                                                                                                                                                                             * @param userId 用户ID
    //                                                                                                                                                                                                                                                                                                                                                                                  * @return 文件元数据列表
    //                                                                                                                                                                                                                                                                                                                                                                                       */
    //                                                                                                                                                                                                                                                                                                                                                                                           @GetMapping("/list")
    //                                                                                                                                                                                                                                                                                                                                                                                               public ResponseEntity<List<FileMetadata>> listUserFiles(@RequestParam("userId") Long userId) {
    //                                                                                                                                                                                                                                                                                                                                                                                                       try {
    //                                                                                                                                                                                                                                                                                                                                                                                                                   // 1. 从数据库查询用户文件列表
    //                                                                                                                                                                                                                                                                                                                                                                                                                               List<FileMetadata> fileList = fileMetadataMapper.selectByUserId(userId);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                           return new ResponseEntity<>(fileList, HttpStatus.OK);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                   } catch (Exception e) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                               e.printStackTrace();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 接口3：文件下载（根据文件ID）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     * @param fileId 文件ID
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @return 文件输入流（供前端下载）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   @GetMapping("/download")
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       public ResponseEntity<InputStream> downloadFile(@RequestParam("fileId") Long fileId) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               try {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // 1. 从数据库查询文件信息
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       FileMetadata fileMetadata = fileMetadataMapper.selectByFileId(fileId);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   if (fileMetadata == null) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   return new ResponseEntity<>(null, HttpStatus.NOT_FOUND);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // 2. 调用 HDFS 工具类下载文件，获取输入流
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       InputStream inputStream = hdfsUtil.downloadFile(fileMetadata.getFilePath());
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   // 3. 设置响应头（支持前端下载文件）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               HttpHeaders headers = new HttpHeaders();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           headers.setContentType(MediaType.APPLICATION_OCTET_STREAM);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       // 解决中文文件名乱码问题
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   headers.setContentDispositionFormData("attachment", new String(fileMetadata.getFileName().getBytes("UTF-8"), "ISO-8859-1"));
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return new ResponseEntity<>(inputStream, headers, HttpStatus.OK);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       } catch (Exception e) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   e.printStackTrace();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               /**
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    * 接口4：文件删除（根据文件ID）
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         * @param fileId 文件ID
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              * @return 删除结果
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   */
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       @DeleteMapping("/delete")
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           public ResponseEntity<String> deleteFile(@RequestParam("fileId") Long fileId) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   try {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // 1. 从数据库查询文件信息
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           FileMetadata fileMetadata = fileMetadataMapper.selectByFileId(fileId);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (fileMetadata == null) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return new ResponseEntity<>("删除失败：文件不存在", HttpStatus.NOT_FOUND);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // 2. 调用 HDFS 工具类删除 HDFS 中的文件
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           boolean isHdfsDeleted = hdfsUtil.deleteFile(fileMetadata.getFilePath());
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       if (!isHdfsDeleted) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return new ResponseEntity<>("删除失败：HDFS 文件删除失败", HttpStatus.INTERNAL_SERVER_ERROR);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // 3. 删除数据库中的文件元数据
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           fileMetadataMapper.deleteById(fileId);
    //
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return new ResponseEntity<>("删除成功", HttpStatus.OK);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } catch (Exception e) {
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           e.printStackTrace();
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       return new ResponseEntity<>("删除失败：" + e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
